# Generated by Django 4.0.3 on 2022-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=60)),
                ('zeme', models.CharField(max_length=80)),
                ('zajimavost', models.TextField()),
                ('pocet_obyvatel', models.IntegerField()),
                ('hlavni_mesto', models.BooleanField()),
            ],
        ),
    ]
